[unstable]
build-std = ["core", "alloc", "panic_abort"]
build-std-features = [
  "optimize_for_size",
  "panic_immediate_abort",
]
codegen-backend = true

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "espflash flash -B 921600 -M -L defmt"
rustflags = [
  "-Cforce-frame-pointers=yes",
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tdefmt.x",
  "-Clink-arg=-Tlinkall.x",
]

[env]
DEFMT_LOG = "esp_tls=info"
WIFI_SSID = "ouroboros"
WIFI_PASS = "comeagain"

[profile.dev]
opt-level = "s"
codegen-backend = "llvm"
panic = "abort"
strip = false
debug = true

[profile.release]
opt-level = "s"
codegen-units = 1
codegen-backend = "llvm"
panic = "abort"
strip = false
debug = 2
lto = true
